back to the "AttributeError: 'NoneType' object has no attribute '_inc_path' " and I didnt even do anything except try to create one new record.  So its not the model defns that are directly causing the problem